import { MetricCard, StatusPill } from "@/components/StatusPill";
import { getIterationSnapshot, getRuntimeSnapshot } from "@/lib/data";
import { zhLabel } from "@/lib/i18n";

export const dynamic = "force-dynamic";

export default function OperationsPage() {
  const runtime = getRuntimeSnapshot();
  const iteration = getIterationSnapshot();
  const tests = Object.entries(iteration.tests ?? {});
  return <div className="page-stack"><section className="page-hero"><div><span className="eyebrow">发布运营</span><h1>迭代与部署</h1><p>观察、测试、评估、纸面部署和验证形成发布闭环；本页不提供绕过审批的实盘按钮。</p></div><StatusPill tone={runtime.containerState === "running" ? "green" : "red"}>{zhLabel(runtime.containerState)}</StatusPill></section><section className="metric-grid"><MetricCard label="容器状态" value={zhLabel(runtime.containerState)} hint={runtime.container} tone={runtime.containerState === "running" ? "green" : "red"} /><MetricCard label="报告年龄" value={runtime.reportAgeHours === null ? "—" : `${runtime.reportAgeHours.toFixed(1)} 小时`} hint={runtime.reportStale ? "需要重新采集" : "数据新鲜"} tone={runtime.reportStale ? "amber" : "green"} /><MetricCard label="代码版本" value={runtime.gitHead} hint={`${runtime.gitDirtyCount} 个工作树变更`} tone={runtime.gitDirtyCount ? "amber" : "green"} /><MetricCard label="最近迭代" value={iteration.generated_at || "—"} hint="历史报告生成时间" /></section><section className="two-column"><div className="panel"><div className="panel-head"><div><span className="eyebrow">检查项</span><h2>测试门禁</h2></div></div><div className="check-rows">{tests.length ? tests.map(([name, result]) => <div key={name}><StatusPill tone={result.ok ? "green" : "red"}>{result.ok ? "通过" : "失败"}</StatusPill><strong>{zhLabel(name)}</strong></div>) : <div className="empty-state">尚无测试快照</div>}</div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">运行状态</span><h2>部署事实</h2></div></div><dl className="facts"><div><dt>项目根目录</dt><dd>{runtime.root}</dd></div><div><dt>容器</dt><dd>{runtime.container}</dd></div><div><dt>数据可信度</dt><dd>{runtime.reportStale ? "历史快照，不能作为当前运行证明" : "当前快照"}</dd></div><div><dt>实盘权限</dt><dd>默认关闭，需要显式审批</dd></div></dl></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">自动迭代</span><h2>自动迭代闭环</h2></div></div><div className="pipeline">{["观察","测试","评估","制定修复计划","部署纸面实例","验证","晋级或回滚"].map((step, index) => <div className="pipeline-step" key={step}><span>{index + 1}</span><strong>{step}</strong></div>)}</div></section></div>;
}
