node {
    def app
    def tag = 'development'
    def buildMessage = 'Building and pushing to docker hub... '
    def dockerImage = "coinalpha/hummingbot"
    def dockerTag = "coinalpha/hummingbot:${tag}-${env.BUILD_NUMBER}"
    def gitCommit = env.GIT_COMMIT

    try {
      notifyBuild('STARTED')

      stage('Clone repository') {
          /* Clone repository to jenkins workspace */
          checkout scm
      }

      stage('Build image') {
          /* This builds the actual image; synonymous to
          * docker build on the command line */

          // Update VERSION
          sh "echo dev-${env.GIT_COMMIT}-${env.BUILD_TIMESTAMP} > hummingbot/VERSION"

          app = docker.build(dockerImage)
      }

      stage('Test image') {
          /* Ideally, we would run a test framework against our image.
          * For this example, we're using a Volkswagen-type approach ;-) */
          app.inside {
              sh 'echo "python test"'
          }
      }

      stage('Push image') {
          /* Finally, we'll push the image with two tags:
          * First, the incremental build number from Jenkins
          * Second, the 'latest' tag.
          * Pushing multiple tags is cheap, as all the layers are reused. */
          docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
              app.push("${tag}-${env.BUILD_NUMBER}")
              app.push("${tag}")
          }
          def description = ":docker: Successfully pushed to `${dockerTag}`"
          discordSend (webhookURL: env.DISCORD_URL, description: description, result: 'SUCCESS')
      }
    } catch (c) {
      // If there was an exception thrown, the build failed
      currentBuild.result = "FAILED"
      throw e      
    } finally {
      // Success or failure, always send notifications
      notifyBuild(currentBuild.result)
    }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def result = 'FAILURE'

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    buildStatus = 'Building and pushing to docker hub... '
    result = 'UNSTABLE'
  } else if (buildStatus == 'SUCCESSFUL') {
    result = 'SUCCESS'
  }

  def subject = ":docker: ${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def description = "${subject} (${env.BUILD_URL})"

  // Send notifications
  discordSend (webhookURL: env.DISCORD_URL, description: description, result: result)
}