def testName = "xemm strategy"
sh "echo Starting ${testName}"

node {

    try {
      sh "echo 'try: notify build'"
 
      notifyBuild("STARTED")

      stage("Clone repository") {
        /* Clone repository to jenkins workspace */
        checkout scm
      }

      stage("Build hummingbot") {
        // Clean-up environment
        sh "conda deactivate"
        sh "./uninstall"
        sh "./install"
        sh "conda activate hummingbot"
        sh "./compile"
      }

      stage("Run tests") {
        sh "echo run tests"
        sh "python test/cross_exchange_market_making.py"
      }

    } catch (c) {
      // If there was an exception thrown, the tests failed
      sh "echo 'catch: '${c}"
 
      currentBuild.result = "FAILED"
      throw e      
    } finally {
      sh "echo finally"

      // Success or failure, always send notifications
      notifyBuild(currentBuild.result)
    }
}

def notifyBuild(String buildStatus = "STARTED") {
  sh "echo call notifyBuild"
  // build status of null means successful
  buildStatus =  buildStatus ?: "SUCCESSFUL"

  // Default values
  def result = "FAILURE"

  // Override default values based on build status
  if (buildStatus == "STARTED") {
    buildStatus = "Initiating ${testName} test... "
    result = "UNSTABLE"
  } else if (buildStatus == "SUCCESSFUL") {
    result = "SUCCESS"
  }

  def subject = "${buildStatus}: Job [${env.JOB_NAME}_${env.BUILD_NUMBER}]"
  def description = "${subject} (${env.BUILD_URL})"

  // Send notifications
  discordSend (webhookURL: env.DISCORD_URL, description: description, result: result)
}