#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    sudo -u abc /bin/bash -c "source /opt/conda/bin/activate && conda init"
fi
