#!/bin/bash

cd $(dirname $0)

source $(dirname "$0")/common_install.sh

echo "*** Installing Conda environment for Hummingbot ***"

CONDA_EXE=$(find_conda_exe) || exit 1

CONDA_BIN=$(dirname ${CONDA_EXE})

_ENV_DIR="setup"
ENV_FILE="environment.yml"

ENV_FILE=$(get_env_file "${_ENV_DIR}/${ENV_FILE}")

ENV_NAME=$(get_env_name "${_ENV_DIR}/${ENV_FILE}")

if ${CONDA_EXE} env list | awk '{ print $1 }' | egrep -e "^${ENV_NAME}$" 1>/dev/null; then
    ${CONDA_EXE} env update -f "${_ENV_DIR}/${ENV_FILE}" --prune
else
    ${CONDA_EXE} env create -f "${_ENV_DIR}/${ENV_FILE}"
fi

# Record updated environment file
${CONDA_EXE} env export -n ${ENV_NAME} > "${_ENV_DIR}/.installed:${ENV_FILE}"

source "${CONDA_BIN}/activate" ${ENV_NAME}

# Installing conflicting pip packages without their dependencies
# They could override the environment plan with conda
echo "Installing conflicting pip packages without their dependencies"
pip install --no-deps -r setup/pip_packages.txt 1> logs/pip_install.log 2>&1
pre-commit install
