#!/bin/bash

PASSWORD=""

# Argument parsing
while getopts ":p:" opt; do
  case $opt in
    p)
      PASSWORD="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Check if bin/hummingbot_quickstart.py exists
if [[ ! -f bin/hummingbot_quickstart.py ]]; then
    echo "Error: bin/hummingbot_quickstart.py command not found. Make sure you are in the Hummingbot root directory"
    exit 1
fi

# Check if the hummingbot conda environment is activated
if [[ $CONDA_DEFAULT_ENV != "hummingbot" ]]; then
    echo "Error: 'hummingbot' conda environment is not activated. Please activate it and try again."
    exit 1
fi

# If a password was provided, pass it to the Python script
if [[ ! -z "$PASSWORD" ]]; then
    ./bin/hummingbot_quickstart.py -p "$PASSWORD" 2>> ./logs/errors.log
else
    ./bin/hummingbot_quickstart.py 2>> ./logs/errors.log
fi
