#!/bin/bash

# Check if bin/hummingbot_quickstart.py exists
if [[ ! -f bin/hummingbot_quickstart.py ]]; then
    echo "Error: bin/hummingbot_quickstart.py command not found. Make sure you are in the Hummingbot root directory"
    exit 1
fi

# Check if the hummingbot conda environment is activated
if [[ $CONDA_DEFAULT_ENV != "hummingbot" ]]; then
    echo "Error: 'hummingbot' conda environment is not activated. Please activate it and try again."
    exit 1
fi

# Run bin/hummingbot.py and append errors to logs/errors.log
./bin/hummingbot_quickstart.py 2>> ./logs/errors.log
