#!/bin/bash

cd $(dirname $0)

# Compatibility logic for older Anaconda versions.
if [ "${CONDA_EXE} " == " " ]; then
    CONDA_EXE=$((find /opt/conda/bin/conda || find ~/anaconda3/bin/conda || \
	    find /usr/local/anaconda3/bin/conda || find ~/miniconda3/bin/conda  || \
	    find /root/miniconda/bin/conda || find ~/Anaconda3/Scripts/conda) 2>/dev/null)
fi

if [ "${CONDA_EXE}_" == "_" ]; then
    echo "Please install Anaconda w/ Python 3.7+ first"
    echo "See: https://www.continuum.io/downloads"
    exit 1
fi

MACOS_ENV=setup/environment.yml
LINUX_ENV=setup/environment-linux.yml
LINUX_AARCH64_ENV=setup/environment-linux-aarch64.yml
WIN64_ENV=setup/environment-win64.yml
ENV_FILE=$MACOS_ENV

if uname | egrep -qe "Linux"; then
    if uname -m | egrep -qe "aarch64"; then
        ENV_FILE=$LINUX_AARCH64_ENV
    else
        ENV_FILE=$LINUX_ENV
    fi
elif uname | egrep -qe "MINGW64"; then
    ENV_FILE=$WIN64_ENV
fi

VALID_ENV_NAME=$(grep  'name:' ${ENV_FILE} | tail -n1 | awk '{ print $2}')
read -p "Enter environment name [${VALID_ENV_NAME}]: " RESPONSE
if [ "${RESPONSE}_" == "_" ]; then
    RESPONSE=${VALID_ENV_NAME}
fi

ENV_NAME=${RESPONSE}
echo    "   Attempting to remove: ${ENV_NAME}"

if ${CONDA_EXE} env list | awk '{ print $1 }' | egrep -e "^${ENV_NAME}$" 1>/dev/null; then
    echo "   Environment found."
    echo "       Environment .yml: ${ENV_FILE}"
    VALID_ENV_NAME=$(grep  'name:' ${ENV_FILE} | tail -n1 | awk '{ print $2}')
    echo "          .yml env name: ${VALID_ENV_NAME}"

    if [ ${ENV_NAME} != ${VALID_ENV_NAME} ]; then
        echo "*** You are attempting to remove the environment:"
        echo "       ${ENV_NAME}"
        echo "    but the environment name in ${ENV_FILE} is:"
        echo "       ${VALID_ENV_NAME}"
    fi

    read -p "Do you want to continue? [y/N]: " RESPONSE
    if [ "${RESPONSE}_" == "_" ] || [ "${RESPONSE}" != "y" ]; then
        echo "Aborting."
        exit 1
    fi

    ${CONDA_EXE} env remove -n ${ENV_NAME}
else
    echo "Environment already removed."
fi
