name: "Install environment and Hummingbot"
description: "Installs pixi environment and compiles Hummingbot"
inputs:
   program-cache-hit:
     required: true
     description: "Value of truth regarding the program cache being hit or not"
runs:
  using: "composite"
  steps:
    - name: Set up pixi
      if: ${{inputs.program-cache-hit}} != 'true'
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        environments: ci
        cache: true

    - name: Build Hummingbot
      shell: bash
      if: ${{inputs.program-cache-hit}} != 'true'
      run: pixi run -e ci build
