node {
    def app
    def tag = 'development'
    def buildMessage = 'Building and pushing to docker hub... '
    def dockerImage = "coinalpha/hummingbot"
    def dockerTag = "coinalpha/hummingbot:${tag}-${env.BUILD_NUMBER}"

    try {
      notifyBuild('STARTED')

      stage('Clone repository') {
          /* Clone repository to jenkins workspace */
          checkout scm
      }

      stage('Pre-build Docker system prune') {
          /* Clean up docker environment */
          sh "docker system prune -fa"
      }

      stage('Build image') {
          /* Build docker image */
          app = docker.build(dockerImage)
      }

      stage('Test image') {
          /* Testing place holder */
          app.inside {
              sh 'echo "python test"'
          }
      }

      stage('Push image') {
          // Get VERSION for tag labeling
          def version = readFile('hummingbot/VERSION').trim()

          /* Push docker image */
          docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
              app.push("${version}")
              app.push("latest")
          }
          def description = "New Docker image pushed to `${dockerImage}:[latest|${version}]`\nhttps://hub.docker.com/r/coinalpha/hummingbot/tags"
          discordSend (webhookURL: env.DISCORD_DEV_URL, description: description, result: 'SUCCESS')
      }

      stage('Post-build Docker system prune') {
          /* Clean up docker environment */
          sh "docker system prune -fa"
      }

    } catch (c) {
      // If there was an exception thrown, the build failed
      currentBuild.result = "FAILED"
      throw e      
    } finally {
      // Success or failure, always send notifications
      notifyBuild(currentBuild.result)
    }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def result = 'FAILURE'

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    buildStatus = 'Building and pushing to docker hub... '
    result = 'UNSTABLE'
  } else if (buildStatus == 'SUCCESSFUL') {
    result = 'SUCCESS'
  }

  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def description = "${subject} (${env.BUILD_URL})"

  // Send notifications
  discordSend (webhookURL: env.DISCORD_URL, description: description, result: result)
}
