from typing import Dict

from hummingbot.strategy_v2.routers.data_types import MarketRegime, StrategyCandidate, StrategyFamily


def default_strategy_registry() -> Dict[str, StrategyCandidate]:
    """
    Registry of strategy candidates that the router can reason about.

    Phase 1 routes directly to executor-backed implementations. The controller_name
    values document the mature Hummingbot controllers that can be promoted later.
    """
    candidates = [
        # Direct executor-backed routes used by the Phase 1 router.
        StrategyCandidate(
            name="grid_strike",
            family=StrategyFamily.GRID,
            controller_name="grid_strike",
            executor_type="grid_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="由网格执行器驱动的区间策略。",
            priority=10,
        ),
        StrategyCandidate(
            name="bollingrid",
            family=StrategyFamily.GRID,
            controller_name="bollingrid",
            executor_type="grid_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="使用布林带过滤的网格候选。",
            priority=20,
        ),
        StrategyCandidate(
            name="multi_grid_strike",
            family=StrategyFamily.GRID,
            controller_name="multi_grid_strike",
            executor_type="grid_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="多网格资金分配候选；直接路由前需要资金分配适配器。",
            priority=60,
            enabled=False,
        ),
        StrategyCandidate(
            name="quantum_grid_allocator",
            family=StrategyFamily.GRID,
            controller_name="quantum_grid_allocator",
            executor_type="grid_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="网格资金分配候选；直接路由前需要状态适配器。",
            priority=65,
            enabled=False,
        ),
        StrategyCandidate(
            name="trend_long",
            family=StrategyFamily.TREND,
            controller_name="supertrend_v1",
            executor_type="position_executor",
            supported_regimes=[
                MarketRegime.TREND_UP,
                MarketRegime.BREAKOUT_UP,
            ],
            description="用于上升趋势行情的多头仓位执行器。",
            priority=10,
        ),
        StrategyCandidate(
            name="trend_short",
            family=StrategyFamily.TREND,
            controller_name="supertrend_v1",
            executor_type="position_executor",
            supported_regimes=[
                MarketRegime.TREND_DOWN,
                MarketRegime.BREAKOUT_DOWN,
            ],
            description="用于下降趋势行情的空头仓位执行器。",
            priority=10,
        ),

        # Directional controller candidates. These are in the strategy universe, but
        # Phase 1 only routes directional exposure through trend_long/trend_short.
        StrategyCandidate(
            name="supertrend_v1",
            family=StrategyFamily.TREND,
            controller_name="supertrend_v1",
            executor_type="position_executor",
            supported_regimes=[
                MarketRegime.TREND_UP,
                MarketRegime.TREND_DOWN,
                MarketRegime.BREAKOUT_UP,
                MarketRegime.BREAKOUT_DOWN,
            ],
            description="超级趋势适配器已注册；通过验证门禁前保持影子状态。",
            priority=40,
            enabled=False,
        ),
        StrategyCandidate(
            name="macd_bb_v1",
            family=StrategyFamily.TREND,
            controller_name="macd_bb_v1",
            executor_type="position_executor",
            supported_regimes=[
                MarketRegime.TREND_UP,
                MarketRegime.TREND_DOWN,
                MarketRegime.BREAKOUT_UP,
                MarketRegime.BREAKOUT_DOWN,
            ],
            description="指数平滑异同移动平均线与布林带方向控制器；需要信号适配器。",
            priority=45,
            enabled=False,
        ),
        StrategyCandidate(
            name="dman_v3",
            family=StrategyFamily.TREND,
            controller_name="dman_v3",
            executor_type="dca_executor",
            supported_regimes=[MarketRegime.TREND_UP, MarketRegime.TREND_DOWN],
            description="方向性定额分批控制器；需要分批风险适配器。",
            priority=50,
            enabled=False,
        ),
        StrategyCandidate(
            name="ai_livestream",
            family=StrategyFamily.TREND,
            controller_name="ai_livestream",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.TREND_UP, MarketRegime.TREND_DOWN],
            description="外部 AI 信号控制器；验证信号可信度和紧急停止开关前保持关闭。",
            priority=80,
            enabled=False,
        ),
        StrategyCandidate(
            name="donchian_breakout",
            family=StrategyFamily.TREND,
            executor_type="position_executor",
            supported_regimes=[MarketRegime.TREND_UP, MarketRegime.TREND_DOWN,
                               MarketRegime.BREAKOUT_UP, MarketRegime.BREAKOUT_DOWN],
            description="从成熟开源示例收集的唐奇安／海龟突破模式；需要适配器。",
            priority=55,
            enabled=False,
        ),
        StrategyCandidate(
            name="dual_thrust",
            family=StrategyFamily.TREND,
            executor_type="position_executor",
            supported_regimes=[MarketRegime.BREAKOUT_UP, MarketRegime.BREAKOUT_DOWN],
            description="双重推力波动突破模式；完成滚动验证前仅供研究。",
            priority=60,
            enabled=False,
        ),
        StrategyCandidate(
            name="ema_crossover",
            family=StrategyFamily.TREND,
            executor_type="position_executor",
            supported_regimes=[MarketRegime.TREND_UP, MarketRegime.TREND_DOWN],
            description="指数移动平均线交叉基准，用作透明的趋势对照。",
            priority=75,
            enabled=False,
        ),

        # Mean-reversion candidates.
        StrategyCandidate(
            name="bollinger_v1",
            family=StrategyFamily.MEAN_REVERSION,
            controller_name="bollinger_v1",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_HIGH_VOL],
            description="布林带均值回归控制器；需要入场和退出评分适配器。",
            priority=45,
            enabled=False,
        ),
        StrategyCandidate(
            name="bollinger_v2",
            family=StrategyFamily.MEAN_REVERSION,
            controller_name="bollinger_v2",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_HIGH_VOL],
            description="第二版布林带均值回归控制器；需要入场和退出评分适配器。",
            priority=45,
            enabled=False,
        ),
        StrategyCandidate(
            name="rsi2_mean_reversion",
            family=StrategyFamily.MEAN_REVERSION,
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="短周期相对强弱指标均值回归模式；需要感知费用的适配器和验证。",
            priority=60,
            enabled=False,
        ),
        # Market-making candidates.
        StrategyCandidate(
            name="pmm_dynamic",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="pmm_dynamic",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL],
            description="面向平静订单簿的动态做市候选；需要纯做市层级适配器。",
            priority=30,
            enabled=False,
        ),
        StrategyCandidate(
            name="pmm_simple",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="pmm_simple",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL],
            description="简单纯做市控制器；需要库存偏斜和仅挂单适配器。",
            priority=35,
            enabled=False,
        ),
        StrategyCandidate(
            name="pmm_v1",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="pmm_v1",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL],
            description="通用第一版纯做市控制器；需要库存和价差适配器。",
            priority=40,
            enabled=False,
        ),
        StrategyCandidate(
            name="pmm_mister",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="pmm_mister",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="高级纯做市适配器已注册；通过验证门禁前保持影子状态。",
            priority=45,
            enabled=False,
        ),
        StrategyCandidate(
            name="dman_maker_v2",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="dman_maker_v2",
            executor_type="dca_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="分批挂单做市控制器；需要分批执行和做市库存适配器。",
            priority=50,
            enabled=False,
        ),
        StrategyCandidate(
            name="avellaneda_market_making",
            family=StrategyFamily.MARKET_MAKING,
            controller_name="avellaneda_market_making",
            executor_type="order_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL],
            description="来自 Hummingbot V1 的库存感知阿维拉内达做市模型；需要 V2 适配器。",
            priority=55,
            enabled=False,
        ),
        StrategyCandidate(
            name="order_book_imbalance_mm",
            family=StrategyFamily.MARKET_MAKING,
            executor_type="order_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="从生产级交易引擎示例收集的订单簿失衡报价模式。",
            priority=65,
            enabled=False,
        ),

        # Arbitrage and relative-value candidates. They need multi-market feature
        # inputs before the single-symbol Phase 1 router can activate them.
        StrategyCandidate(
            name="arbitrage_controller",
            family=StrategyFamily.ARBITRAGE,
            controller_name="arbitrage_controller",
            executor_type="arbitrage_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="套利候选；实盘路由前需要价差特征。",
            priority=50,
            enabled=False,
        ),
        StrategyCandidate(
            name="xemm_multiple_levels",
            family=StrategyFamily.ARBITRAGE,
            controller_name="xemm_multiple_levels",
            executor_type="xemm_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="跨交易所做市候选；需要挂单方与吃单方价差特征。",
            priority=55,
            enabled=False,
        ),
        StrategyCandidate(
            name="stat_arb",
            family=StrategyFamily.ARBITRAGE,
            controller_name="stat_arb",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="统计配对套利控制器；需要配对特征引擎和对冲约束。",
            priority=60,
            enabled=False,
        ),
        StrategyCandidate(
            name="spot_perpetual_basis",
            family=StrategyFamily.ARBITRAGE,
            controller_name="spot_perpetual_arbitrage",
            executor_type="arbitrage_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="来自 Hummingbot 成熟策略族的现货—永续基差收敛策略。",
            priority=45,
            enabled=False,
        ),
        StrategyCandidate(
            name="amm_cex_arbitrage",
            family=StrategyFamily.ARBITRAGE,
            controller_name="amm_arb",
            executor_type="arbitrage_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="链上做市池与中心化交易所的可执行价差策略；需要 Gas、滑点和终局性适配器。",
            priority=65,
            enabled=False,
        ),

        # Hedge and liquidity-management candidates.
        StrategyCandidate(
            name="hedge_asset",
            family=StrategyFamily.HEDGE,
            controller_name="hedge_asset",
            executor_type="order_executor",
            supported_regimes=[MarketRegime.EXTREME, MarketRegime.RANGE_HIGH_VOL],
            description="资产对冲控制器；路由前需要组合敞口输入。",
            priority=70,
            enabled=False,
        ),
        StrategyCandidate(
            name="funding_rate_arb",
            family=StrategyFamily.HEDGE,
            controller_name="v2_funding_rate_arb",
            executor_type="position_executor",
            supported_regimes=[MarketRegime.ARBITRAGE],
            description="资金费率套利适配器已注册；通过验证门禁前保持影子状态。",
            priority=70,
            enabled=False,
        ),
        StrategyCandidate(
            name="lp_rebalancer",
            family=StrategyFamily.LP,
            controller_name="lp_rebalancer",
            executor_type="lp_executor",
            supported_regimes=[MarketRegime.RANGE_LOW_VOL, MarketRegime.RANGE_HIGH_VOL],
            description="流动性再平衡候选；路由前需要链上做市池和网关上下文。",
            priority=80,
            enabled=False,
        ),

        # Observation-only candidates.
        StrategyCandidate(
            name="market_status_monitor",
            family=StrategyFamily.OBSERVE,
            controller_name="examples.market_status_controller",
            supported_regimes=[MarketRegime.UNKNOWN],
            description="仅观察的市场状态控制器。",
            priority=90,
            enabled=False,
        ),
        StrategyCandidate(
            name="liquidations_monitor",
            family=StrategyFamily.OBSERVE,
            controller_name="examples.liquidations_monitor_controller",
            supported_regimes=[MarketRegime.EXTREME],
            description="为风险特征提供数据的仅观察强平监控器。",
            priority=90,
            enabled=False,
        ),
        StrategyCandidate(
            name="protect_mode",
            family=StrategyFamily.PROTECT,
            supported_regimes=[MarketRegime.EXTREME, MarketRegime.UNKNOWN],
            description="停止新增风险，并由风险门禁控制退出。",
            priority=0,
        ),
    ]
    return {candidate.name: candidate for candidate in candidates}
