class FixtureBeaxy:

    BALANCES = [
        {
            "symbol": "BXYBTC",
            "name": "BXYBTC",
            "minimumQuantity": 2500.0,
            "maximumQuantity": 250000.0,
            "quantityIncrement": 1.0,
            "quantityPrecision": 0,
            "tickSize": 1e-08,
            "baseCurrency": "BXY",
            "termCurrency": "BTC",
            "pricePrecision": 8,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "DASHBTC",
            "name": "DASHBTC",
            "minimumQuantity": 0.01,
            "maximumQuantity": 218.32,
            "quantityIncrement": 1e-05,
            "quantityPrecision": 3,
            "tickSize": 1e-06,
            "baseCurrency": "DASH",
            "termCurrency": "BTC",
            "pricePrecision": 6,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "ETCBTC",
            "name": "ETCBTC",
            "minimumQuantity": 0.01,
            "maximumQuantity": 2509.41,
            "quantityIncrement": 1e-07,
            "quantityPrecision": 7,
            "tickSize": 1e-07,
            "baseCurrency": "ETC",
            "termCurrency": "BTC",
            "pricePrecision": 7,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "GOBTC",
            "name": "GOBTC",
            "minimumQuantity": 50.0,
            "maximumQuantity": 2000000.0,
            "quantityIncrement": 0.001,
            "quantityPrecision": 0,
            "tickSize": 1e-08,
            "baseCurrency": "GO",
            "termCurrency": "BTC",
            "pricePrecision": 8,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "BTCUSDC",
            "name": "BTCUSDC",
            "minimumQuantity": 0.001,
            "maximumQuantity": 25.0,
            "quantityIncrement": 1e-08,
            "quantityPrecision": 8,
            "tickSize": 0.01,
            "baseCurrency": "BTC",
            "termCurrency": "USDC",
            "pricePrecision": 2,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "ZECBTC",
            "name": "ZECBTC",
            "minimumQuantity": 0.001,
            "maximumQuantity": 369.21,
            "quantityIncrement": 1e-05,
            "quantityPrecision": 3,
            "tickSize": 1e-06,
            "baseCurrency": "ZEC",
            "termCurrency": "BTC",
            "pricePrecision": 6,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "BATBTC",
            "name": "BATBTC",
            "minimumQuantity": 0.1,
            "maximumQuantity": 90909.09,
            "quantityIncrement": 0.001,
            "quantityPrecision": 6,
            "tickSize": 1e-08,
            "baseCurrency": "BAT",
            "termCurrency": "BTC",
            "pricePrecision": 8,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "XRPBTC",
            "name": "XRPBTC",
            "minimumQuantity": 0.1,
            "maximumQuantity": 81632.65,
            "quantityIncrement": 0.0001,
            "quantityPrecision": 4,
            "tickSize": 1e-08,
            "baseCurrency": "XRP",
            "termCurrency": "BTC",
            "pricePrecision": 8,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": True,
        },
        {
            "symbol": "ALEPHETH",
            "name": "ALEPHETH",
            "minimumQuantity": 20.0,
            "maximumQuantity": 50000.0,
            "quantityIncrement": 1.0,
            "quantityPrecision": 0,
            "tickSize": 1e-08,
            "baseCurrency": "ALEPH",
            "termCurrency": "ETH",
            "pricePrecision": 8,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "crypto",
            "suspendedForTrading": False,
        },
        {
            "symbol": "BTCUSD",
            "name": "BTCUSD",
            "minimumQuantity": 0.001,
            "maximumQuantity": 25.0,
            "quantityIncrement": 1e-08,
            "quantityPrecision": 8,
            "tickSize": 0.01,
            "baseCurrency": "BTC",
            "termCurrency": "USD",
            "pricePrecision": 2,
            "buyerTakerCommissionProgressive": 0.25,
            "buyerMakerCommissionProgressive": 0.15,
            "sellerTakerCommissionProgressive": 0.25,
            "sellerMakerCommissionProgressive": 0.15,
            "type": "fiat",
            "suspendedForTrading": False,
        },
    ]

    TRADE_BOOK = {
        "type": "SNAPSHOT_FULL_REFRESH",
        "security": "DASHBTC",
        "timestamp": 1612206339765,
        "sequenceNumber": 213148,
        "entries": [
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 0,
                "numberOfOrders": None,
                "quantity": 0.5,
                "price": 0.003065,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 1,
                "numberOfOrders": None,
                "quantity": 1.25,
                "price": 0.003066,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 2,
                "numberOfOrders": None,
                "quantity": 2.5,
                "price": 0.003067,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 3,
                "numberOfOrders": None,
                "quantity": 5.0,
                "price": 0.003068,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 4,
                "numberOfOrders": None,
                "quantity": 7.5,
                "price": 0.003069,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 0,
                "numberOfOrders": None,
                "quantity": 0.5,
                "price": 0.003053,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 1,
                "numberOfOrders": None,
                "quantity": 1.25,
                "price": 0.003052,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 2,
                "numberOfOrders": None,
                "quantity": 2.5,
                "price": 0.003051,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 3,
                "numberOfOrders": None,
                "quantity": 5.0,
                "price": 0.00305,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 4,
                "numberOfOrders": None,
                "quantity": 7.5,
                "price": 0.003049,
            },
        ],
    }

    EXCHANGE_RATE = {
        "ask": 0.003264,
        "bid": 0.003256,
        "low24": 0.00152,
        "high24": 0.0055755,
        "volume24": 0.0326,
        "change24": -36.43365506483377,
        "price": 0.003236,
        "volume": 0.01,
        "timestamp": 1612345560000,
    }

    ACCOUNTS = [
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ETH",
            "id": "6F0C6353-B145-41A1-B695-2DCF4DFD8ADD",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "NRG",
            "id": "FD739CEF-3FB7-4885-9A52-41A0A1C570EA",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "NEO",
            "id": "20E33E7E-6940-4521-B3CB-DC75FD9DE0EA",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "2500.19579418",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "2500.19579418",
            "status": "active",
            "available_for_withdrawal": "2500.19579418",
            "total_statistics": [
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "deposit",
                },
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "withdrawal",
                },
                {
                    "total": "7500",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "credit",
                },
                {
                    "total": "-4722",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "execution",
                },
                {
                    "total": "-277.80420582",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "trading_commission",
                },
            ],
            "currency_id": "BXY",
            "id": "1FB1DD29-406B-4227-AE2A-700D8EDCE001",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "AION",
            "id": "64BFCB9A-1E19-4A71-AF2E-FE8344F66B56",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "WAVES",
            "id": "F801485E-774A-472C-A4D4-CCEEF4AC4C21",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ETC",
            "id": "6D555386-2091-4C9E-B4FD-7F575F0D9753",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ZRX",
            "id": "C9C2C810-44AB-48FE-A81F-02B72F9FC87D",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "TOMO",
            "id": "54F5AAB9-3608-46F1-BBA8-F0996FFACE0A",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "USDT",
            "id": "A7383484-784E-48AB-8F8A-62304FF7C37A",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0.00011809",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0.00011809",
            "status": "active",
            "available_for_withdrawal": "0.00011809",
            "total_statistics": [
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "deposit",
                },
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "withdrawal",
                },
                {
                    "total": "0.00017202",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "execution",
                },
                {
                    "total": "-0.00005393",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "trading_commission",
                },
            ],
            "currency_id": "BTC",
            "id": "4C49C9F6-A594-43F1-A351-22C8712596CA",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "BEAM",
            "id": "B916B506-177A-4359-86F2-80D1845B22B5",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "BAT",
            "id": "2200FC9C-B559-4C70-9605-926E28193605",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "35.67478",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "35.67478",
            "status": "active",
            "available_for_withdrawal": "35.67478",
            "total_statistics": [
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "deposit",
                },
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "withdrawal",
                },
                {
                    "total": "80",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "credit",
                },
                {
                    "total": "-44.32522",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "execution",
                },
            ],
            "currency_id": "USDC",
            "id": "9B2ADE73-CE5D-45EE-9788-3587DDCF58F2",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "XRP",
            "id": "71AF49AC-54A4-4F5A-A3A1-97CFEFE40430",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "LTC",
            "id": "8FA31F5A-7A94-4CF6-BA95-9990E9B4C76A",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "GUNTHY",
            "id": "974AB4C0-6EDE-4EFF-BCA1-1F8FAEE93AA6",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ICX",
            "id": "D2CF87AB-754E-4FCD-BB42-7FC812931402",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "DRGN",
            "id": "53BDA6C6-5C66-4BD7-BE63-D547699525A4",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ALEPH",
            "id": "3D0863E2-7AE9-4478-ABED-1FECAF86B639",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "POLY",
            "id": "91A87666-6590-45A8-B70F-FA28EFD32716",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0.05",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0.05",
            "status": "active",
            "available_for_withdrawal": "0.05",
            "total_statistics": [
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "deposit",
                },
                {
                    "total": "0",
                    "total_this_day": "0",
                    "total_this_week": "0",
                    "total_this_month": "0",
                    "type": "withdrawal",
                },
                {
                    "total": "0.05",
                    "total_this_day": None,
                    "total_this_week": None,
                    "total_this_month": None,
                    "type": "execution",
                },
            ],
            "currency_id": "DASH",
            "id": "0B0C8512-A113-4D57-B4C6-D059746B302D",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "LINK",
            "id": "4B4E0955-4DA7-404F-98AE-D0AFF654A0E7",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "FTM",
            "id": "90030F73-36FE-4651-9A59-5E57464F64E6",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "ZEC",
            "id": "44ED1E64-BC45-45DF-B186-2444B8279354",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "BSV",
            "id": "35A5F10B-1A9E-47E4-BA27-8918D1A16F8E",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "HIVE",
            "id": "0E525961-F6D2-422F-87C1-1A82E325DC8A",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "BCH",
            "id": "8A409D82-D049-41C1-A4D2-5F4BA3AF0432",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "GO",
            "id": "DA08BE6A-83B7-481A-BD06-5A2BE79E80E6",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "XSN",
            "id": "03DD4CB5-3BB7-4C74-9FEA-C2CC73123ECE",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "EOS",
            "id": "441649A4-C8A8-445F-8B91-182B5EC9F20D",
            "properties": None,
        },
        {
            "measurement_currency_id": None,
            "available_for_trading": "0",
            "enter_average_price": None,
            "current_price": None,
            "unrealized_pnl": None,
            "realized_pnl": None,
            "balance": "0",
            "status": "active",
            "available_for_withdrawal": "0",
            "total_statistics": None,
            "currency_id": "XMR",
            "id": "81444BA4-EC69-42FE-AD54-09500335788B",
            "properties": None,
        },
    ]

    HEALTH = {"logins": 204, "is_alive": True, "users": 10, "timestamp": 1612207143392}

    SNAPSHOT_MSG = {
        "type": "SNAPSHOT_FULL_REFRESH",
        "security": "DASHBTC",
        "timestamp": 1612345351563,
        "sequenceNumber": 42820,
        "entries": [
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 0,
                "numberOfOrders": None,
                "quantity": 0.5,
                "price": 0.003251,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 1,
                "numberOfOrders": None,
                "quantity": 1.25,
                "price": 0.003252,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 2,
                "numberOfOrders": None,
                "quantity": 2.5,
                "price": 0.003253,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 3,
                "numberOfOrders": None,
                "quantity": 5.0,
                "price": 0.003255,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 4,
                "numberOfOrders": None,
                "quantity": 7.5,
                "price": 0.003256,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 5,
                "numberOfOrders": None,
                "quantity": 10.0,
                "price": 0.003257,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 6,
                "numberOfOrders": None,
                "quantity": 12.5,
                "price": 0.003259,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 7,
                "numberOfOrders": None,
                "quantity": 20.466,
                "price": 0.003264,
            },
            {
                "action": "INSERT",
                "side": "ASK",
                "level": 8,
                "numberOfOrders": None,
                "quantity": 0.5,
                "price": 0.00808,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 0,
                "numberOfOrders": None,
                "quantity": 0.4994,
                "price": 0.00324,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 1,
                "numberOfOrders": None,
                "quantity": 1.25,
                "price": 0.003238,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 2,
                "numberOfOrders": None,
                "quantity": 2.5,
                "price": 0.003237,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 3,
                "numberOfOrders": None,
                "quantity": 5.0,
                "price": 0.003236,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 4,
                "numberOfOrders": None,
                "quantity": 7.5,
                "price": 0.003235,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 5,
                "numberOfOrders": None,
                "quantity": 10.0,
                "price": 0.003234,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 6,
                "numberOfOrders": None,
                "quantity": 12.5,
                "price": 0.003233,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 7,
                "numberOfOrders": None,
                "quantity": 0.533,
                "price": 0.003229,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 8,
                "numberOfOrders": None,
                "quantity": 0.55068,
                "price": 0.002249,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 9,
                "numberOfOrders": None,
                "quantity": 134.24942,
                "price": 1.4e-5,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 10,
                "numberOfOrders": None,
                "quantity": 60.0,
                "price": 1.3e-5,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 11,
                "numberOfOrders": None,
                "quantity": 6.0,
                "price": 1.0e-5,
            },
            {
                "action": "INSERT",
                "side": "BID",
                "level": 12,
                "numberOfOrders": None,
                "quantity": 200.0,
                "price": 6.0e-6,
            },
        ],
    }

    TEST_LIMIT_BUY_ORDER = {
        "average_price": "0",
        "receipt_time": 1612351106032,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "1D37D726-E162-484B-8816-A43B43549CDD",
        "timestamp": 1612351106032,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": "0.003266",
        "client_order_id": "1D37D726-E162-484B-8816-A43B43549CDD",
        "time_in_force": "gtc",
        "price": "0.003266",
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "limit",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_LIMIT_BUY_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user8ea365d0-24a6-83ed-ec03-59bac214fe97\ncontent-type:application/json\nsubscription:sub-humming-1612351104275342\nmessage-id:8ea365d0-24a6-83ed-ec03-59bac214fe97-18\ncontent-length:1397\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"13215876","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.003266","client_order_id":"1D37D726-E162-484B-8816-A43B43549CDD","time_in_force":"gtc","price":"0.003266","expire_time":null,"reason":null,"order_id":"1D37D726-E162-484B-8816-A43B43549CDD","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"limit","order_status":"new","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-8965","type":"submitted","sequence_number":8965,"currency":"DASH","timestamp":1612351106037,"properties":null}],"order":{"average_price":"0","receipt_time":1612351106025,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"1D37D726-E162-484B-8816-A43B43549CDD","timestamp":1612351106037,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.003266","client_order_id":"1D37D726-E162-484B-8816-A43B43549CDD","time_in_force":"gtc","price":"0.003266","expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_LIMIT_BUY_WS_ORDER_COMPLETED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user9d827cdb-52b2-3303-6eba-615683c76ddf\ncontent-type:application/json\nsubscription:sub-humming-1612347898789940\nmessage-id:9d827cdb-52b2-3303-6eba-615683c76ddf-17\ncontent-length:1535\n\n{"events":[{"trade_quantity":"0.01","trade_price":"0.003297","commission":"-0.00000008","original_client_order_id":null,"is_agressor":true,"order_side":"buy","event_id":"0000000000BDBED4","average_price":"0.003297","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.003297","client_order_id":"C715ECA9-D13C-42AE-A978-083F62974B85","time_in_force":"gtc","price":"0.003297","expire_time":null,"reason":null,"order_id":"C715ECA9-D13C-42AE-A978-083F62974B85","cumulative_quantity":"0.01","remaining_quantity":"0","order_type":"limit","order_status":"completely_filled","commission_currency":"BTC","text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-8938","type":"trade","sequence_number":8938,"currency":"DASH","timestamp":1612347915748,"properties":[{"key":"1115","value":"Order"}]}],"order":{"average_price":"0.003297","receipt_time":1612347915627,"close_time":1612347915748,"reason":null,"cumulative_quantity":"0.01","remaining_quantity":"0","status":"completely_filled","id":"C715ECA9-D13C-42AE-A978-083F62974B85","timestamp":1612347915748,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.003297","client_order_id":"C715ECA9-D13C-42AE-A978-083F62974B85","time_in_force":"gtc","price":"0.003297","expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":[{"key":"7224","value":"-0.00000008"}]}}"""

    TEST_LIMIT_SELL_ORDER = {
        "average_price": "0",
        "receipt_time": 1612367046013,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393",
        "timestamp": 1612367046013,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": "0.003118",
        "client_order_id": "E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393",
        "time_in_force": "gtc",
        "price": "0.003118",
        "expire_time": None,
        "text": "HBOT-sell-DASH-BTC-1",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "sell",
        "type": "limit",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_LIMIT_SELL_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user9cb6b7b3-b47b-97ac-59dd-76e5b33b5953\ncontent-type:application/json\nsubscription:sub-humming-1612367042528182\nmessage-id:9cb6b7b3-b47b-97ac-59dd-76e5b33b5953-20\ncontent-length:1402\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"sell","event_id":"18102008","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.003118","client_order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","time_in_force":"gtc","price":"0.003118","expire_time":null,"reason":null,"order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"limit","order_status":"new","commission_currency":null,"text":"HBOT-sell-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-8998","type":"submitted","sequence_number":8998,"currency":"DASH","timestamp":1612367046019,"properties":null}],"order":{"average_price":"0","receipt_time":1612367046011,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","timestamp":1612367046019,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.003118","client_order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","time_in_force":"gtc","price":"0.003118","expire_time":null,"text":"HBOT-sell-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_LIMIT_SELL_WS_ORDER_COMPLETED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user9cb6b7b3-b47b-97ac-59dd-76e5b33b5953\ncontent-type:application/json\nsubscription:sub-humming-1612367042528182\nmessage-id:9cb6b7b3-b47b-97ac-59dd-76e5b33b5953-21\ncontent-length:1552\n\n{"events":[{"trade_quantity":"0.01","trade_price":"0.003118","commission":"-0.00000008","original_client_order_id":null,"is_agressor":true,"order_side":"sell","event_id":"0000000001143A1A","average_price":"0.003118","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.003118","client_order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","time_in_force":"gtc","price":"0.003118","expire_time":null,"reason":null,"order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","cumulative_quantity":"0.01","remaining_quantity":"0","order_type":"limit","order_status":"completely_filled","commission_currency":"BTC","text":"HBOT-sell-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9004","type":"trade","sequence_number":9004,"currency":"DASH","timestamp":1612367046020,"properties":[{"key":"1115","value":"Order"}]}],"order":{"average_price":"0.003118","receipt_time":1612367046011,"close_time":1612367046020,"reason":null,"cumulative_quantity":"0.01","remaining_quantity":"0","status":"completely_filled","id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","timestamp":1612367046020,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.003118","client_order_id":"E5BA149A-9DD7-4C2E-A2E8-1C37DF6C5393","time_in_force":"gtc","price":"0.003118","expire_time":null,"text":"HBOT-sell-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"limit","source":"CWUI","currency":"DASH","properties":[{"key":"7224","value":"-0.00002565747273893521"}]}}"""

    TEST_UNFILLED_ORDER1 = {
        "average_price": "0",
        "receipt_time": 1612368513007,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "3DE4D10B-6882-4BF8-958A-EA689C145065",
        "timestamp": 1612368513007,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": "0.002496",
        "client_order_id": "3DE4D10B-6882-4BF8-958A-EA689C145065",
        "time_in_force": "gtc",
        "price": "0.002496",
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1612368513006601",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "limit",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_UNFILLED_ORDER2 = {
        "average_price": "0",
        "receipt_time": 1612368513007,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "3DE4D10B-6882-4BF8-958A-EA689C145065",
        "timestamp": 1612368513007,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": "0.002496",
        "client_order_id": "3DE4D10B-6882-4BF8-958A-EA689C145065",
        "time_in_force": "gtc",
        "price": "0.002496",
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1612368513006601",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "limit",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_UNFILLED_ORDER1_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userb0ad4644-7c10-565c-84d0-e1dc576a06f2\ncontent-type:application/json\nsubscription:sub-humming-1612368511313960\nmessage-id:b0ad4644-7c10-565c-84d0-e1dc576a06f2-26\ncontent-length:1397\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"18699442","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.002496","client_order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","time_in_force":"gtc","price":"0.002496","expire_time":null,"reason":null,"order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"limit","order_status":"new","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1612368513006601","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9067","type":"submitted","sequence_number":9067,"currency":"DASH","timestamp":1612368513011,"properties":null}],"order":{"average_price":"0","receipt_time":1612368512949,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"3DE4D10B-6882-4BF8-958A-EA689C145065","timestamp":1612368513011,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.002496","client_order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","time_in_force":"gtc","price":"0.002496","expire_time":null,"text":"HBOT-buy-DASH-BTC-1612368513006601","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_UNFILLED_ORDER2_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userb0ad4644-7c10-565c-84d0-e1dc576a06f2\ncontent-type:application/json\nsubscription:sub-humming-1612368511313960\nmessage-id:b0ad4644-7c10-565c-84d0-e1dc576a06f2-27\ncontent-length:1398\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"sell","event_id":"18699800","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.00311","client_order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","time_in_force":"gtc","price":"0.00311","expire_time":null,"reason":null,"order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"limit","order_status":"new","commission_currency":null,"text":"HBOT-sell-DASH-BTC-1612368514001761","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9078","type":"submitted","sequence_number":9078,"currency":"DASH","timestamp":1612368514021,"properties":null}],"order":{"average_price":"0","receipt_time":1612368513974,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","timestamp":1612368514021,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.00311","client_order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","time_in_force":"gtc","price":"0.00311","expire_time":null,"text":"HBOT-sell-DASH-BTC-1612368514001761","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_UNFILLED_ORDER1_WS_ORDER_CANCELED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userb0ad4644-7c10-565c-84d0-e1dc576a06f2\ncontent-type:application/json\nsubscription:sub-humming-1612368511313960\nmessage-id:b0ad4644-7c10-565c-84d0-e1dc576a06f2-28\ncontent-length:1497\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"18701450","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.002496","client_order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","time_in_force":"gtc","price":"0.002496","expire_time":null,"reason":"Manual cancelation from tradingapi.beaxy.com","order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","cumulative_quantity":"0","remaining_quantity":"0","order_type":"limit","order_status":"canceled","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1612368513006601","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9089","type":"cancel","sequence_number":9089,"currency":"DASH","timestamp":1612368517010,"properties":null}],"order":{"average_price":"0","receipt_time":1612368512949,"close_time":1612368517010,"reason":"Manual cancelation from tradingapi.beaxy.com","cumulative_quantity":"0","remaining_quantity":"0.01","status":"canceled","id":"3DE4D10B-6882-4BF8-958A-EA689C145065","timestamp":1612368517010,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.002496","client_order_id":"3DE4D10B-6882-4BF8-958A-EA689C145065","time_in_force":"gtc","price":"0.002496","expire_time":null,"text":"HBOT-buy-DASH-BTC-1612368513006601","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_UNFILLED_ORDER2_WS_ORDER_CANCELED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userb0ad4644-7c10-565c-84d0-e1dc576a06f2\ncontent-type:application/json\nsubscription:sub-humming-1612368511313960\nmessage-id:b0ad4644-7c10-565c-84d0-e1dc576a06f2-29\ncontent-length:1498\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"sell","event_id":"18701522","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.00311","client_order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","time_in_force":"gtc","price":"0.00311","expire_time":null,"reason":"Manual cancelation from tradingapi.beaxy.com","order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","cumulative_quantity":"0","remaining_quantity":"0","order_type":"limit","order_status":"canceled","commission_currency":null,"text":"HBOT-sell-DASH-BTC-1612368514001761","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9100","type":"cancel","sequence_number":9100,"currency":"DASH","timestamp":1612368517226,"properties":null}],"order":{"average_price":"0","receipt_time":1612368513974,"close_time":1612368517226,"reason":"Manual cancelation from tradingapi.beaxy.com","cumulative_quantity":"0","remaining_quantity":"0.01","status":"canceled","id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","timestamp":1612368517226,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.00311","client_order_id":"9C4B5661-7C66-4AEF-AD5D-F6E813228F2A","time_in_force":"gtc","price":"0.00311","expire_time":null,"text":"HBOT-sell-DASH-BTC-1612368514001761","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""

    TEST_MARKET_BUY_ORDER = {
        "average_price": "0",
        "receipt_time": 1612371213996,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "E7444777-4AAC-43D9-9AF2-61BE027D42ED",
        "timestamp": 1612371213996,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": None,
        "client_order_id": "E7444777-4AAC-43D9-9AF2-61BE027D42ED",
        "time_in_force": "ioc",
        "price": None,
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "market",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_MARKET_BUY_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userc2959dab-c524-e54c-b973-1aec61426cce\ncontent-type:application/json\nsubscription:sub-humming-1612371211987894\nmessage-id:c2959dab-c524-e54c-b973-1aec61426cce-35\ncontent-length:1375\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"19742404","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"market","order_status":"new","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9229","type":"submitted","sequence_number":9229,"currency":"DASH","timestamp":1612371214001,"properties":null}],"order":{"average_price":"0","receipt_time":1612371213978,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","timestamp":1612371214001,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"market","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_MARKET_BUY_WS_ORDER_COMPLETED = """MESSAGE\nstatus:200\ndestination:/v1/orders-userc2959dab-c524-e54c-b973-1aec61426cce\ncontent-type:application/json\nsubscription:sub-humming-1612371211987894\nmessage-id:c2959dab-c524-e54c-b973-1aec61426cce-36\ncontent-length:1513\n\n{"events":[{"trade_quantity":"0.01","trade_price":"0.003075","commission":"-0.00000008","original_client_order_id":null,"is_agressor":true,"order_side":"buy","event_id":"00000000012D41E6","average_price":"0.003075","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","cumulative_quantity":"0.01","remaining_quantity":"0","order_type":"market","order_status":"completely_filled","commission_currency":"BTC","text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9235","type":"trade","sequence_number":9235,"currency":"DASH","timestamp":1612371214001,"properties":[{"key":"1115","value":"Order"}]}],"order":{"average_price":"0.003075","receipt_time":1612371213978,"close_time":1612371214001,"reason":null,"cumulative_quantity":"0.01","remaining_quantity":"0","status":"completely_filled","id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","timestamp":1612371214001,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"E7444777-4AAC-43D9-9AF2-61BE027D42ED","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"market","source":"CWUI","currency":"DASH","properties":[{"key":"7224","value":"-0.00000008"}]}}"""

    TEST_MARKET_SELL_ORDER = {
        "average_price": "0",
        "receipt_time": 1612371349993,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "770AE260-895C-41DF-A5E9-E67904E7F8C0",
        "timestamp": 1612371349993,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": None,
        "client_order_id": "770AE260-895C-41DF-A5E9-E67904E7F8C0",
        "time_in_force": "ioc",
        "price": None,
        "expire_time": None,
        "text": "HBOT-sell-DASH-BTC-1",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "sell",
        "type": "market",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_MARKET_SELL_WS_ORDER_CREATED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user178e98a8-ccf2-0706-1d57-e30f5e9b91ba\ncontent-type:application/json\nsubscription:sub-humming-1612371349761545\nmessage-id:178e98a8-ccf2-0706-1d57-e30f5e9b91ba-37\ncontent-length:1380\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"sell","event_id":"19803703","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"market","order_status":"new","commission_currency":null,"text":"HBOT-sell-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9262","type":"submitted","sequence_number":9262,"currency":"DASH","timestamp":1612371349999,"properties":null}],"order":{"average_price":"0","receipt_time":1612371349955,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","timestamp":1612371349999,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-sell-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"market","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_MARKET_SELL_WS_ORDER_COMPLETED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user178e98a8-ccf2-0706-1d57-e30f5e9b91ba\ncontent-type:application/json\nsubscription:sub-humming-1612371349761545\nmessage-id:178e98a8-ccf2-0706-1d57-e30f5e9b91ba-38\ncontent-length:1530\n\n{"events":[{"trade_quantity":"0.01","trade_price":"0.003057","commission":"-0.00000008","original_client_order_id":null,"is_agressor":true,"order_side":"sell","event_id":"00000000012E3159","average_price":"0.003057","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","cumulative_quantity":"0.01","remaining_quantity":"0","order_type":"market","order_status":"completely_filled","commission_currency":"BTC","text":"HBOT-sell-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9268","type":"trade","sequence_number":9268,"currency":"DASH","timestamp":1612371350000,"properties":[{"key":"1115","value":"Order"}]}],"order":{"average_price":"0.003057","receipt_time":1612371349955,"close_time":1612371350000,"reason":null,"cumulative_quantity":"0.01","remaining_quantity":"0","status":"completely_filled","id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","timestamp":1612371350000,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"770AE260-895C-41DF-A5E9-E67904E7F8C0","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-sell-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"market","source":"CWUI","currency":"DASH","properties":[{"key":"7224","value":"-0.00002616944717042852"}]}}"""

    TEST_CANCEL_BUY_ORDER = {
        "average_price": "0",
        "receipt_time": 1612373138029,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "C24200B6-A16B-46C6-88A2-6D348671B25E",
        "timestamp": 1612373138029,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": "0.001544",
        "client_order_id": "C24200B6-A16B-46C6-88A2-6D348671B25E",
        "time_in_force": "gtc",
        "price": "0.001544",
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "limit",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_CANCEL_BUY_WS_ORDER_COMPLETED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user1b8f7a06-858e-c0dc-8665-a99fb892c363\ncontent-type:application/json\nsubscription:sub-humming-1612373137250051\nmessage-id:1b8f7a06-858e-c0dc-8665-a99fb892c363-45\ncontent-length:1397\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"20424624","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.001544","client_order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","time_in_force":"gtc","price":"0.001544","expire_time":null,"reason":null,"order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"limit","order_status":"new","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9389","type":"submitted","sequence_number":9389,"currency":"DASH","timestamp":1612373138034,"properties":null}],"order":{"average_price":"0","receipt_time":1612373137964,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"C24200B6-A16B-46C6-88A2-6D348671B25E","timestamp":1612373138034,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.001544","client_order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","time_in_force":"gtc","price":"0.001544","expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_CANCEL_BUY_WS_ORDER_CANCELED = """MESSAGE\nstatus:200\ndestination:/v1/orders-user1b8f7a06-858e-c0dc-8665-a99fb892c363\ncontent-type:application/json\nsubscription:sub-humming-1612373137250051\nmessage-id:1b8f7a06-858e-c0dc-8665-a99fb892c363-46\ncontent-length:1497\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"buy","event_id":"20425042","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":"0.001544","client_order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","time_in_force":"gtc","price":"0.001544","expire_time":null,"reason":"Manual cancelation from tradingapi.beaxy.com","order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","cumulative_quantity":"0","remaining_quantity":"0","order_type":"limit","order_status":"canceled","commission_currency":null,"text":"HBOT-buy-DASH-BTC-1","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"BTC-9400","type":"cancel","sequence_number":9400,"currency":"DASH","timestamp":1612373139033,"properties":null}],"order":{"average_price":"0","receipt_time":1612373137964,"close_time":1612373139033,"reason":"Manual cancelation from tradingapi.beaxy.com","cumulative_quantity":"0","remaining_quantity":"0.01","status":"canceled","id":"C24200B6-A16B-46C6-88A2-6D348671B25E","timestamp":1612373139033,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":"0.001544","client_order_id":"C24200B6-A16B-46C6-88A2-6D348671B25E","time_in_force":"gtc","price":"0.001544","expire_time":null,"text":"HBOT-buy-DASH-BTC-1","destination":"MAXI","security_id":"DASHBTC","side":"buy","type":"limit","source":"CWUI","currency":"DASH","properties":null}}"""

    TEST_CANCEL_ALL_ORDER1 = {
        "average_price": "0",
        "receipt_time": 1612372497032,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "3F5C5F5D-A4BE-4E7A-903C-B8FADB708050",
        "timestamp": 1612372497032,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": None,
        "client_order_id": "3F5C5F5D-A4BE-4E7A-903C-B8FADB708050",
        "time_in_force": "ioc",
        "price": None,
        "expire_time": None,
        "text": "HBOT-buy-DASH-BTC-1612372497005401",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "buy",
        "type": "market",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_CANCEL_ALL_ORDER2 = {
        "average_price": "0",
        "receipt_time": 1612372497226,
        "close_time": 0,
        "reason": None,
        "cumulative_quantity": "0",
        "remaining_quantity": "0.01",
        "status": "pending_new",
        "id": "5484A8B3-8C06-4C83-AFC3-B01EB500AD09",
        "timestamp": 1612372497226,
        "stop_price": None,
        "leverage": None,
        "submission_time": None,
        "quantity": "0.01",
        "limit_price": None,
        "client_order_id": "5484A8B3-8C06-4C83-AFC3-B01EB500AD09",
        "time_in_force": "ioc",
        "price": None,
        "expire_time": None,
        "text": "HBOT-sell-DASH-BTC-1612372497005441",
        "destination": "MAXI",
        "security_id": "DASHBTC",
        "side": "sell",
        "type": "market",
        "source": "CWUI",
        "currency": None,
        "properties": None,
    }
    TEST_CANCEL_BUY_WS_ORDER1_CANCELED = """MESSAGE\nstatus:200\ndestination:/v1/orders-usere53ecdd6-383c-ef5d-1d1f-5471624e0ad9\ncontent-type:application/json\nsubscription:sub-humming-1612372490957013\nmessage-id:e53ecdd6-383c-ef5d-1d1f-5471624e0ad9-43\ncontent-length:1380\n\n{"events":[{"trade_quantity":null,"trade_price":null,"commission":null,"original_client_order_id":null,"is_agressor":null,"order_side":"sell","event_id":"20206349","average_price":"0","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","cumulative_quantity":"0","remaining_quantity":"0.01","order_type":"market","order_status":"new","commission_currency":null,"text":"HBOT-sell-DASH-BTC-1612372497005441","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9356","type":"submitted","sequence_number":9356,"currency":"DASH","timestamp":1612372497234,"properties":null}],"order":{"average_price":"0","receipt_time":1612372497184,"close_time":0,"reason":null,"cumulative_quantity":"0","remaining_quantity":"0.01","status":"new","id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","timestamp":1612372497234,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-sell-DASH-BTC-1612372497005441","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"market","source":"CWUI","currency":"DASH","properties":null}}"""
    TEST_CANCEL_BUY_WS_ORDER2_CANCELED = """MESSAGE\nstatus:200\ndestination:/v1/orders-usere53ecdd6-383c-ef5d-1d1f-5471624e0ad9\ncontent-type:application/json\nsubscription:sub-humming-1612372490957013\nmessage-id:e53ecdd6-383c-ef5d-1d1f-5471624e0ad9-44\ncontent-length:1530\n\n{"events":[{"trade_quantity":"0.01","trade_price":"0.003068","commission":"-0.00000008","original_client_order_id":null,"is_agressor":true,"order_side":"sell","event_id":"000000000134562F","average_price":"0.003068","stop_price":null,"leverage":null,"quantity":"0.01","limit_price":null,"client_order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","time_in_force":"ioc","price":null,"expire_time":null,"reason":null,"order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","cumulative_quantity":"0.01","remaining_quantity":"0","order_type":"market","order_status":"completely_filled","commission_currency":"BTC","text":"HBOT-sell-DASH-BTC-1612372497005441","exchange_id":null,"destination":"MAXI","security_id":"DASHBTC","id":"DASH-9362","type":"trade","sequence_number":9362,"currency":"DASH","timestamp":1612372497236,"properties":[{"key":"1115","value":"Order"}]}],"order":{"average_price":"0.003068","receipt_time":1612372497184,"close_time":1612372497236,"reason":null,"cumulative_quantity":"0.01","remaining_quantity":"0","status":"completely_filled","id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","timestamp":1612372497236,"stop_price":null,"leverage":null,"submission_time":null,"quantity":"0.01","limit_price":null,"client_order_id":"5484A8B3-8C06-4C83-AFC3-B01EB500AD09","time_in_force":"ioc","price":null,"expire_time":null,"text":"HBOT-sell-DASH-BTC-1612372497005441","destination":"MAXI","security_id":"DASHBTC","side":"sell","type":"market","source":"CWUI","currency":"DASH","properties":[{"key":"7224","value":"-0.00002607561929595828"}]}}"""
