# coding=utf-8

SYMBOL_TYPE_SPOT = 'SPOT'

ORDER_STATUS_SYSTEM_PROCESSING = '-2'
ORDER_STATUS_NEW = '0'
ORDER_STATUS_PARTIALLY_FILLED = '1'
ORDER_STATUS_FILLED = '2'
ORDER_STATUS_CANCELED = '3'
ORDER_STATUS_PENDING_CANCEL = '4'
ORDER_STATUS_REJECTED = '5'
ORDER_STATUS_EXPIRED = '6'

KLINE_INTERVAL_1MINUTE = '1m'
KLINE_INTERVAL_3MINUTE = '3m'
KLINE_INTERVAL_5MINUTE = '5m'
KLINE_INTERVAL_15MINUTE = '15m'
KLINE_INTERVAL_30MINUTE = '30m'
KLINE_INTERVAL_1HOUR = '1h'
KLINE_INTERVAL_2HOUR = '2h'
KLINE_INTERVAL_4HOUR = '4h'
KLINE_INTERVAL_6HOUR = '6h'
KLINE_INTERVAL_8HOUR = '8h'
KLINE_INTERVAL_12HOUR = '12h'
KLINE_INTERVAL_1DAY = '1d'
KLINE_INTERVAL_3DAY = '3d'
KLINE_INTERVAL_1WEEK = '1w'
KLINE_INTERVAL_1MONTH = '1M'

SIDE_BUY = '0'
SIDE_SELL = '1'

ORDER_TYPE_LIMIT = '1'
ORDER_TYPE_MARKET = '2'
ORDER_TYPE_STOP_LOSS = '3'
ORDER_TYPE_STOP_LOSS_LIMIT = '4'
ORDER_TYPE_TAKE_PROFIT = '5'
ORDER_TYPE_TAKE_PROFIT_LIMIT = '6'
ORDER_TYPE_LIMIT_MAKER = '7'

TIME_IN_FORCE_GTC = 'GTC'  # Good till cancelled
TIME_IN_FORCE_IOC = 'IOC'  # Immediate or cancel
TIME_IN_FORCE_FOK = 'FOK'  # Fill or kill

ORDER_RESP_TYPE_ACK = 'ACK'
ORDER_RESP_TYPE_RESULT = 'RESULT'
ORDER_RESP_TYPE_FULL = 'FULL'

WEBSOCKET_DEPTH_5 = '5'
WEBSOCKET_DEPTH_10 = '10'
WEBSOCKET_DEPTH_20 = '20'
